"""empty message

Revision ID: b951fc21a078
Revises: 805591eb739d
Create Date: 2022-08-24 15:41:14.708235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b951fc21a078'
down_revision = '805591eb739d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livro', 'autor')
    op.drop_column('livro', 'editora')
    op.drop_column('livro', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livro', sa.Column('nome', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('livro', sa.Column('editora', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('livro', sa.Column('autor', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
